package constant

// PORTS
const PORT_ADMIN_API = "8081"
const PORT_HTTP = "8080"
const PORT_HTTPS = "8443"

// PROTOCOLS
const UTF_8 = "UTF-8"
const HS_256 = "HS256"
const RSA_256 = "RS256"

var AVAILABLE_PROXY_PROTOCOLS = []string{"http", "https"}

// HTTP
var VALID_METHODS = []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"}

// PLUGINS
var AVAILABLE_PLUGINS = []string{
	PLUGIN_BASIC_AUTH,
	PLUGIN_ACL,
	PLUGIN_BOT_PROTECTION,
	PLUGIN_RATE_LIMIT,
	PLUGIN_REQUEST_SIZE_LIMIT,
	PLUGIN_REQUEST_TERMINATION,
	PLUGIN_JWT,
	PLUGIN_KEY_AUTH,
	PLUGIN_MTLS,
	PLUGIN_HTTP_LOG,
	PLUGIN_CORS,
	PLUGIN_HEADER_TRANSFORMATION,
	PLUGIN_CIRCUIT_BREAKER,
	PLUGIN_RBAC,
	PLUGIN_SANITIZATION,
	PLUGIN_CACHE,
	PLUGIN_SHADOW_TRAFFIC,
	PLUGIN_MULTI_AUTH,
	PLUGIN_PROMETHEUS,
	PLUGIN_OPENTELEMETRY,
}

const PLUGIN_RESPONSE_HANDLER = "response-handler"
const PLUGIN_BASIC_AUTH = "basic-auth"
const PLUGIN_ACL = "acl"
const PLUGIN_CORS = "cors"
const PLUGIN_BOT_PROTECTION = "bot-protection"
const PLUGIN_RATE_LIMIT = "rate-limiting"
const PLUGIN_REQUEST_SIZE_LIMIT = "request-size-limiting"
const PLUGIN_JWT = "jwt"
const PLUGIN_KEY_AUTH = "key-auth"
const PLUGIN_MTLS = "mtls"
const PLUGIN_HTTP_LOG = "http-log"
const PLUGIN_HEADER_TRANSFORMATION = "header-transformation"
const PLUGIN_CIRCUIT_BREAKER = "circuit-breaker"
const PLUGIN_RBAC = "rbac"
const PLUGIN_SANITIZATION = "sanitization"
const PLUGIN_CACHE = "cache"
const PLUGIN_SHADOW_TRAFFIC = "shadow-traffic"
const PLUGIN_MULTI_AUTH = "multi-auth"
const PLUGIN_PROMETHEUS = "prometheus"
const PLUGIN_OPENTELEMETRY = "opentelemetry"
const PLUGIN_REQUEST_TERMINATION = "request-termination"
