version: "3.8"

networks:
  sushi-net:


services:
  # Redis - Required for Gateway plugins
  sushi-redis:
    image: redis:7-alpine
    container_name: sushi-redis
    networks:
      - sushi-net
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backends
  sushi-svc-1:
    networks:
      - sushi-net
    container_name: sushi-svc-1
    image: rawsashimi/express-sushi-app
    ports:
      - "8001:3000"
    environment:
      APP_ID: 8001
      JWT_ISSUER: someIssuerKey
      JWT_SECRET: 123secret456

  sushi-svc-2:
    networks:
      - sushi-net
    container_name: sushi-svc-2
    image: rawsashimi/express-sushi-app
    ports:
      - "8002:3000"
    environment:
      APP_ID: 8002
      JWT_ISSUER: someIssuerKey
      JWT_SECRET: 123secret456

  sushi-svc-3:
    networks:
      - sushi-net
    container_name: sushi-svc-3
    image: rawsashimi/express-sushi-app
    ports:
      - "8003:3000"
    environment:
      APP_ID: 8003
      JWT_ISSUER: someIssuerKey
      JWT_SECRET: 123secret456

  sushi-http-log-consumer:
    networks:
      - sushi-net
    container_name: sushi-http-log-consumer
    image: rawsashimi/express-sushi-http-consumer
    ports:
      - "3030:3000"

  # Sushi Gateway Proxy
  sushi-gateway-proxy:
    networks:
      - sushi-net
    container_name: sushi-proxy
    build:
      context: ./sushi-proxy
      dockerfile: Dockerfile
    ports:
      - "8008:8008" # Proxy Port
      - "8081:8081" # Admin Port
      - "8443:8443" # HTTPS Port
    environment:
      CONFIG_FILE_PATH: "/app/config.yaml"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "changeme"
      PERSISTENCE_CONFIG: "dbless"
      REDIS_ADDR: "sushi-redis:6379"
      REDIS_PASSWORD: ""
    volumes:
      - ./sushi-proxy/config/config.yaml:/app/config.yaml
    depends_on:
      sushi-redis:
        condition: service_healthy

  # Sushi Manager UI
  sushi-manager:
    networks:
      - sushi-net
    container_name: sushi-manager
    build:
      context: ./sushi-manager
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      # This replaces the literal string "SUSHI_MANAGER_BACKEND_API_URL" in the built frontend
      - VITE_BACKEND_API_URL=http://localhost:8081

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
